name: Generate Sitemap

on:
  push:
    branches:
      - main # Or whatever your primary branch is (e.g., master)
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Crucial for accurate 'lastmod' dates based on commit history

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v2.0.0 # Use the latest stable version if available, or specify v2.0.0 as this is reliable
        with:
          # IMPORTANT: Use your custom domain here, not the github.io URL
          base-url-path: https://michaelvincentpt.com.au/
          
          # Adjust if your site files are in a subdirectory (e.g., 'docs').
          # For most GitHub Pages sites, '.' is correct if your HTML is at the root.
          path-to-root: . 
          
          # Exclude paths you don't want indexed (e.g., a 404 page, admin sections)
          exclude-paths: "404.html" # Example
          
          # Set to true if your website serves URLs without the .html extension (e.g., /about instead of /about.html)
          # Ensure your internal links and canonical tags match this setting.
          drop-html-extension: false 
          
          # Set to true if you only want dates, not full timestamps, in <lastmod>
          date-only: false

      - name: Commit and push sitemap
        # Use EndBug/add-and-commit for committing the generated file
        uses: EndBug/add-and-commit@v10 # Latest stable version at time of writing
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Docs: Generate and update sitemap.xml via GitHub Actions'
          add: 'sitemap.xml' # The file generated by the sitemap action
          branch: ${{ github.ref_name }} # Push to the same branch that triggered the workflow